### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MovingtoMars** [felixangell/yash-kernel#2]
Hey, I'd like to use your `gdt.c` in my hobby kernel, but there isn't any license info here. May I have permission please (or an open source license added)?

**Comment by felixangell** [comment]
Go for it :)

**Comment by felixangell** [comment]
Added a license too.

**Comment by MovingtoMars** [comment]
Ah, the ol' WTFPL. Thanks. I might upload my kernel to github sometime.

**Comment by felixangell** [comment]
@MovingtoMars Aye, no problem. And yeah do it, sounds interesting :+1:

**Comment by MovingtoMars** [comment]
@felixangell Yeah. Will you be on IRC tonight (in your timezone)?

**Comment by felixangell** [comment]
@MovingtoMars I can go on now for an hour or so, and I'll be on later (5 hours ish?)
